config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tests
  root to: 'static_pages#home'
  get 'login' , to: 'aaa#new'
  post 'login' , to: 'aaa#create'
  get 'logout' , to: 'aaa#destroy'
  get 'test' , to: 'aaa#test'
  get '/custom_token/:id',to: 'firebase_tokens#show_token'
  get '/room/:receiver_id/:sender_id',to: 'chat_rooms#show_the_room'
  post 'friendships' , to: 'friendships#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  validates :uname, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :friendships, dependent: :destroy
    validates :uname, uniqueness: true
    has_secure_password
end

app/controllers/aaa_controller.rb
class AaaController < ApplicationController
    def create
        p params
        p "aaaaaaaaaaaaaaaaaaaa"
        p params[:aaa][:uname]
        @user = User.find_by(uname: params[:aaa][:uname])
        if @user && @user.authenticate(params[:aaa][:password])
            session[:user_uname] = @user.uname
            flash[:info] = "logged in as #{@user.uname}"
            redirect_to root_path
        else
            flash[:danger] = 'invalid email/password combination'
            redirect_to root_path
        end
    end
    
    def new

    end
    
    def test
        if current_user
            flash[:danger] = 'invalid email/password combination'
            redirect_to root_path
        else
            flash[:danger] = 'invalid email/d combination'
            redirect_to root_path
        end
    end
    
    def destroy
        session[:user_uname] = nil
        flash[:info] = "logged out"
        redirect_to root_path
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by(uname: session[:user_uname])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    def show_a_room
        @firebase_uid = "nnn"
        @custom_token = FirebaseTokensController.get_custom_token(@firebase_uid)
    end
    
    def show_the_room
        @current_user = current_user
        if @current_user.uname == params[:receiver_id]
            @firebase_uid = params[:receiver_id]
            @custom_token = FirebaseTokensController.get_custom_token(@firebase_uid)
            @receiver_id = params[:receiver_id]
            @sender_id = params[:sender_id]
        else
            flash[:info] = "nnnnnnn"
            redirect_to root_path
        end
    end
end

app/controllers/firebase_tokens_controller.rb
class FirebaseTokensController < ActionController::Base
    def self.get_custom_token(uid)
        auth_file = File.join(Rails.root, 'config','chat-d235b49900e9.json')
        auth_data = open(auth_file) do |data|
            JSON.load(data)
        end
        service_account_email = auth_data['client_email']
        private_key = OpenSSL::PKey::RSA.new auth_data['private_key']
        now_seconds = Time.now.to_i
        payload = {
      :iss => service_account_email,
      :sub => service_account_email,
      :aud => 'https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit',
      :iat => now_seconds,
      :exp => now_seconds + ( 60 * 60 ), # Maximum expiration time is one hour
      :uid => uid,
      :claims => {:premium_account => false}
        }
        JWT.encode(payload, private_key, 'RS256')
    end
    
    def show_token
        uid = params[:id]
        data = {"uid" => uid,"token" => FirebaseTokensController.get_custom_token(uid)}
        render :json => data
    end
    
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def create
        if current_user
            p params 
            fship = current_user.friendships.new(:uname => params[:aaa][:uname])
            if fship.save
                flash[:info] = "friendships added"
                redirect_to root_path
            else
                flash[:info] = "追加できません。"
                redirect_to root_path
            end
        else
          flash[:info] = "please login"
          redirect_to root_path
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @current_user = current_user
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:aaa)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:info] = "user created"
      redirect_to root_path
    else
      render :new 
    end
    
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uname, :mail, :password, :password_confirmation)
    end
end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aaa/new.html.erb
<h1>login</h1>

    <%= form_for(:aaa, url: login_path) do |f| %>

      <%= f.label :uname %>
      <%= f.text_field :uname, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

app/views/chat_rooms/show_the_room.html.erb
    <!-- update the version number as needed -->
  
    <script src="https://www.gstatic.com/firebasejs/4.1.3/firebase.js"></script>
<body>

 <h1><%= @receiver_id %> - <%= @sender_id %></h1>
    <div id="message">
        
        <input type="text" name="" id="my_text">
      <input type="button" value="送信" onclick="changeData()">
    </div>
<ul id="ssss"></ul>

  </body>
<script>
sanitaize = {
  encode : function (str) {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  },

  decode : function (str) {
    return str.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, '\'').replace(/&amp;/g, '&');
  }
};
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyDmyb3BGG_KylUGBZgr0YVmEGychTif0vA",
    authDomain: "chat-57cf2.firebaseapp.com",
    databaseURL: "https://chat-57cf2.firebaseio.com",
    projectId: "chat-57cf2",
    storageBucket: "chat-57cf2.appspot.com",
    messagingSenderId: "677325226607"
  };
  firebase.initializeApp(config);
  firebase.auth().signInWithCustomToken("<%= @custom_token %>").catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // ...
});
        var db = firebase.database();
      var myChatAll = db.ref("/msg/<%= @receiver_id %>/<%= @sender_id %>");
      var myChatAllrev = db.ref("/msg/<%= @sender_id %>/<%= @receiver_id %>");
      function changeData(){
        var text = document.getElementById("my_text").value;
        myChatAll.push({title:"example", text:text});
        myChatAllrev.push({title:"example", text:text});
      }
      var e = document.getElementById('ssss');
      var elemLi = document.createElement('li');
      elemLi.textContent = "aaaaaa";
      myChatAll.once("value", function(snapshot) { 
        document.getElementById("chatText").innerText = snapshot.val().text;
        Object.keys(snapshot.val()).forEach(function (key) {
          var elemLi = document.createElement('li');
          elemLi.textContent = sanitaize.encode(snapshot.val()[key]["text"]);
        });
      });
      
      myChatAll.on('child_added', function(snapshot) { 
        var elemLi = document.createElement('li');
        elemLi.textContent = sanitaize.encode(snapshot.val()["text"]); 
        e.insertBefore(elemLi,e.firstChild);
      });
</script>
  </head>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myline</title>
    <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
llllllllllllllllllllllll

app/views/static_pages/home.html.erb
<h1>メッセージ交換</h1>
<%= link_to "login",login_path =%><br>
<%= link_to "sign up",new_user_path =%><br>
<%= link_to "logout",logout_path =%><br>

<% flash.each do |key, value| %>
<h1><%= value %></h1>
<% end %>


<%= form_for(:aaa, url: friendships_path) do |f| %>
<%= f.label "uname" %>
<%= f.text_field "uname", class: 'form-control' %>
<%= f.submit "友達を追加する", class: "btn btn-primary" %>
<% end %>

<% if @current_user %>
<h2>あなたのunameは「<%= @current_user.uname %>」</h2>
<h2>友達リスト</h2>
<%   @current_user.friendships.each do |fr| %> 
   <p><%= fr.uname %> </p>
   <a href = "<%= "/room/" + @current_user.uname + "/" +fr.uname %>"  >会話へ</a>
<%  end %> 
<% end %>

<h4>使い方</h4>
1.サインアップ<br>
2.ログイン<br>
3.他のunameを指定して友達を追加<br>
4.会話へ

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname %>
    <%= f.text_field :uname %>
  </div>

  <div class="field">
    <%= f.label :mail %>
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Uname</th>
      <th>Mail</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.uname %></td>
        <td><%= user.mail %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uname:</strong>
  <%= @user.uname %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>